### ISSUE TITLE
Support aarch64 docker images

### ISSUE THREAD

**Issue by superherointj** [nix-community/docker-nixpkgs#22]
Any plan to support aarch64 nix images?

Workaround:
In [pkgs.nix](https://github.com/nix-community/docker-nixpkgs/blob/debbce24255ddc862decf9b643584b077efa82e4/pkgs.nix), change `x86_64-linux` to `aarch64-linux` and build (`nix-build -A nix-flakes`)

**Comment by Mic92** [comment]
I think the major block is a aarch64 ci builder.

**Comment by superherointj** [comment]
> I think the major block is a aarch64 ci builder.

I have a local aarch64 cluster (5 x RockPro64; 3 x Raspberry Pi 4) running NixOS/k3s with spare capacity that I use for gitlab runners. I could add this project for building and uploading images (while a better answer doesn't come up).

Question is if this would be acceptable regarding security. I cannot guarantee I have taken all security precautions to make it secure. And I don't like having responsibility much. But I think community wise we need these images. I mean, instead of having nothing, having something might be better?

In case this is desirable, I'd schedule builds for overnight. Let me know.

**Comment by Mic92** [comment]
I would leave this decision to @zimbatm

**Comment by zimbatm** [comment]
@Mic92 what do you think if we add a GitHub Actions agent on the aarch64 box that we have now?

**Comment by Mic92** [comment]
@zimbatm yes, why not.

**Comment by vincentbernat** [comment]
Hey! Is there a blocker with the proposed solution? I would also be quited interested by having aarch64 images.

**Comment by Mic92** [comment]
hercules-ci does aarch64.
