### ISSUE TITLE
`test` in latest tag fails to properly test for executable files

### ISSUE THREAD

**Issue by silverraven691** [nix-community/docker-nixpkgs#24]
Hello,

We're witnessing the following: `test -x exe` in today's `:latest` tag is incorrectly returning `1`
```sh
$ export IMAGE=nixpkgs/nix@sha256:7d18385c919113f3495226e39f7b8b915743fc14edcd867a38107a9868c2e5f4 # :latest from today
$ docker run -it --rm $IMAGE sh -c 'touch exe; chmod +x exe; test -x exe && echo OK || echo KO'
KO
$ export IMAGE=nixpkgs/nix@sha256:8536a25f261194d033dd8124a72181393471aba0e1c2309aeb242fd38df59aa5 # Previous :latest (we believe)
$ docker run -it --rm $IMAGE sh -c 'touch exe; chmod +x exe; test -x exe && echo OK || echo KO'
OK
$ export IMAGE=nixpkgs/nix@sha256:b391ea0473d8dd3eb76b7ff69f012abab8915c2a48595c3d022cd5674e611834 # :nixos-20.09 from today
$ docker run -it --rm $IMAGE sh -c 'touch exe; chmod +x exe; test -x exe && echo OK || echo KO'
OK
```

This has manifested itself in our GitLab CI pipelines with the message `shell not found`, for their CI runner tests for common shell paths, and as `test` is returning false negatives, it fails to start the script.

I don't doubt the source of the issue is somewhere else, but I thought reporting it here could be helpful.

Thanks

**Comment by zimbatm** [comment]
I'm not able to reproduce the issue unfortunately:
```
$ export IMAGE=nixpkgs/nix@sha256:7d18385c919113f3495226e39f7b8b915743fc14edcd867a38107a9868c2e5f4 # :latest from today
$ docker run -it --rm $IMAGE sh -c 'touch exe; chmod +x exe; test -x exe && echo OK || echo KO'
OK
```

**Comment by silverraven691** [comment]
I've since reinstalled my OS (not NixOS), test on `nixpkgs/nix@sha256:7d18385c919113f3495226e39f7b8b915743fc14edcd867a38107a9868c2e5f4` works properly, and in our GitLab CI runners, `nixpkgs/nix` works properly as well.
:shrug: !
