### ISSUE TITLE
"getDirectoryContents:openDirStream: permission denied" in custom image

### ISSUE THREAD

**Issue by aidalgol** [nix-community/docker-nixpkgs#39]
I have defined an image for [nix-linter](https://github.com/Synthetica9/nix-linter) following the existing images' examples,
```nix
{ buildCLIImage
, nix-linter
}:
buildCLIImage {
  drv = nix-linter;
}
```
and when I try to run it, I get a "permission denied" error:
```console
$ podman run --rm localhost/nix-linter-0.2.0.3:rfj89prik95nb35nrpsrr1cf5ik8323i nix-linter --recursive .
nix-linter: /proc/tty/driver: getDirectoryContents:openDirStream: permission denied (Permission denied)
```
Other images from this repository run fine under podman, so I don't think it's a podman issue.

**Comment by zimbatm** [comment]
It looks like nix-linter is traversing the whole filesystem and trying to open the `/proc/tty/driver` file and failing.

I think what you wanted to do is not lint the content of the container, but the content of the current folder. If podman works like docker it would look like this:
```console
$ podman run -v `$PWD:/src` --rm localhost/nix-linter-0.2.0.3:rfj89prik95nb35nrpsrr1cf5ik8323i nix-linter --recursive /src
```

**Comment by aidalgol** [comment]
Ah, of course.  That was the problem.  Thank you!
