### ISSUE TITLE
How are you meant to use these images?

### ISSUE THREAD

**Issue by johnae** [nix-community/docker-nixpkgs#4]
I originally left a comment over in https://github.com/nix-community/docker-nix/pull/21 - just repeating it here:

I don't fully understand how docker-nixpkgs are meant to be used. For example, what one probably tries first is:

```
docker run -ti --rm nixpkgs/nix-unstable:latest
```

but then

```
bash-4.4# nix-env -iA nixpkgs.git
error: getting information about '/root/.nix-defexpr': No such file or directory
```

So I'm missing something?

**Comment by johnae** [comment]
Not sure this is by design but to use the nixpkgs/nix image to actually install stuff etc, I had to do this:

```
mkdir -p /etc/nix /root
echo "sandbox = false" >> /etc/nix/nix.conf
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
nix-channel --update
## now I can do stuff
nix-env -iA nixpkgs.git
installing 'git-minimal-2.19.2'
these paths will be fetched (14.36 MiB do,,,,,
```

**Comment by zimbatm** [comment]
Good question.
```
$ docker run -ti --rm nixpkgs/nix-unstable:latest
bash-4.4# nix run nixpkgs.git
[6 copied (87.7 MiB), 25.9 MiB DL]
bash-4.4# echo $NIX_PATH
nixpkgs=channel:nixpkgs-unstable
bash-4.4# 
```

**Comment by johnae** [comment]
Right so I guess what we'd do is to use a nix image as a base for our CI and make changes so that we can do builds and installs as necessary.
